# Generated by Django 4.0.5 on 2022-07-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=15, verbose_name='chat_id')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь Вконтакте',
                'verbose_name_plural': 'Пользователи Вконтакте',
                'ordering': ['-update_date'],
            },
        ),
    ]
