# Generated by Django 4.0.5 on 2022-07-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0003_operator_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
