# Generated by Django 4.0.5 on 2022-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0005_operator_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
